{% set name = "fates-emerald" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NordicESMhub/ctsm/archive/release-emerald-platform{{ version }}.tar.gz
  sha256: d5012572f1fb3f237ba618aef32977a99f6425bf486412fe9f0c8da84b8f1636

build:
  skip: true  # [win or osx]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
  host:
    - python
    - mpich
    - hdf5
    - netcdf-fortran
  run:
    - tcsh
    - python
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - netcdf-fortran
    - mpich
    - libxml2
    - libiconv
    - make
    - cmake
    - mkl
    - wget

test:
  commands:
    - create_newcase --help
    - create_clone --help
    - query_testlists --help
    - query_config --help

about:
  home: https://github.com/NordicESMhub/ctsm/tree/fates_emerald_api
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The EMERALD version of the Functionally Assembled Terrestrial Ecosystem Simulator (FATES) with Community Terrestrial Systems Model as host model is maintained by the University of Oslo.
  doc_url: https://github.com/NordicESMhub/ctsm/blob/fates_emerald_api/README_fates_emerald_api

extra:
  recipe-maintainers:
    - annefou
